package:
  name: test-relink
  version: 0.0.0

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
test:
  commands:
    - otool -L $PREFIX/lib/liba.dylib
    - otool -L $PREFIX/bin/b
    - b
