package:
  name: test-relink
  version: 0.0.0

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
tests:
  - script:
      - otool -l $PREFIX/lib/libabsolute.dylib  | grep -A 2 RPATH
      - otool -l $PREFIX/lib/librelative.dylib  | grep -A 2 RPATH
      - otool -l $PREFIX/bin/test_link  | grep -A 2 RPATH
      - otool -L $PREFIX/lib/libabsolute.dylib $PREFIX/lib/librelative.dylib $PREFIX/bin/test_link
      - test_link
