context:
  name: test-ignore
  version: 0.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

build:
  number: 0

requirements:
tests:
  - files:
      source:
        - ignored
        - included
      recipe:
        - recipe.yaml
    script:
      - pwd
      - ls -la
      - tree .
      - test -f included
      - test -f ignored
