[project]
authors = ["Min RK <benjaminrk@gmail.com>"]
channels = ["conda-forge"]
name = "test-recipe"
platforms = ["osx-arm64"]
version = "0.1.0"

[feature.rattler-build.tasks]
rattler-build = "rattler-build build -v -r recipe"

[feature.rattler-build.dependencies]
rattler-build = "*"

[feature.conda-build.tasks]
conda-build = "conda-build -c conda-forge recipe"

[feature.conda-build.dependencies]
conda-build = "*"

[environments]
rattler-build = { features = ["rattler-build"] }
conda-build = { features = ["conda-build"] }
